/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Song1:String = "event:/Music/Song1";
}

class FmodSFX {
    public static inline var LaserStaticHum:String = "event:/SFX/Enemies/LaserStatic/LaserStaticHum";
    public static inline var LaserStaticHum2:String = "event:/SFX/Enemies/LaserStatic/LaserStaticHum2";
    public static inline var LaserStationaryBlast:String = "event:/SFX/Enemies/LaserStationary/LaserStationaryBlast";
    public static inline var LaserStationaryBlast2:String = "event:/SFX/Enemies/LaserStationary/LaserStationaryBlast2";
    public static inline var LaserStationaryCharge:String = "event:/SFX/Enemies/LaserStationary/LaserStationaryCharge";
    public static inline var LaserTurretBlast:String = "event:/SFX/Enemies/LaserTurret/LaserTurretBlast";
    public static inline var LaserTurretBlast2:String = "event:/SFX/Enemies/LaserTurret/LaserTurretBlast2";
    public static inline var LaserTurretBlast3:String = "event:/SFX/Enemies/LaserTurret/LaserTurretBlast3";
    public static inline var LaserTurretCharge:String = "event:/SFX/Enemies/LaserTurret/LaserTurretCharge";
    public static inline var LaserTurretCharge2:String = "event:/SFX/Enemies/LaserTurret/LaserTurretCharge2";
    public static inline var DoorTick:String = "event:/SFX/Level/Door/DoorTick";
    public static inline var OrbHum:String = "event:/SFX/Level/Orb/OrbHum";
    public static inline var OrbHum2:String = "event:/SFX/Level/Orb/OrbHum2";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var PlayerBonk:String = "event:/SFX/Player/Bonk/PlayerBonk";
    public static inline var PlayerBonkWall:String = "event:/SFX/Player/Bonk/PlayerBonkWall";
    public static inline var PlayerBonkWall2:String = "event:/SFX/Player/Bonk/PlayerBonkWall2";
    public static inline var ColorCharge:String = "event:/SFX/Player/Color/ColorCharge";
    public static inline var ColorCharge2:String = "event:/SFX/Player/Color/ColorCharge2";
    public static inline var ColorFlash:String = "event:/SFX/Player/Color/ColorFlash";
    public static inline var ColorFlash2:String = "event:/SFX/Player/Color/ColorFlash2";
    public static inline var ColorShoot:String = "event:/SFX/Player/Color/ColorShoot";
    public static inline var ColorStart:String = "event:/SFX/Player/Color/ColorStart";
    public static inline var ColorTouch:String = "event:/SFX/Player/Color/ColorTouch";
    public static inline var PlayerDieBurst:String = "event:/SFX/Player/Die/PlayerDieBurst";
    public static inline var PlayerDieBurst2:String = "event:/SFX/Player/Die/PlayerDieBurst2";
    public static inline var PlayerDieHit:String = "event:/SFX/Player/Die/PlayerDieHit";
    public static inline var PlayerDieSwell:String = "event:/SFX/Player/Die/PlayerDieSwell";
    public static inline var PlayerDieSwell2:String = "event:/SFX/Player/Die/PlayerDieSwell2";
    public static inline var PlayerDieSwell3:String = "event:/SFX/Player/Die/PlayerDieSwell3";
    public static inline var PlayerDieSwell4:String = "event:/SFX/Player/Die/PlayerDieSwell4";
    public static inline var PlayerDuck:String = "event:/SFX/Player/Duck/PlayerDuck";
    public static inline var PlayerDuck2:String = "event:/SFX/Player/Duck/PlayerDuck2";
    public static inline var PlayerUnduck:String = "event:/SFX/Player/Duck/PlayerUnduck";
    public static inline var PlayerUnduck2:String = "event:/SFX/Player/Duck/PlayerUnduck2";
    public static inline var PlayerJump1:String = "event:/SFX/Player/Jump/PlayerJump1";
    public static inline var PlayerJump2:String = "event:/SFX/Player/Jump/PlayerJump2";
    public static inline var PlayerJump3:String = "event:/SFX/Player/Jump/PlayerJump3";
    public static inline var PlayerJump3_2:String = "event:/SFX/Player/Jump/PlayerJump3_2";
    public static inline var PlayerJump4:String = "event:/SFX/Player/Jump/PlayerJump4";
    public static inline var PlayerLand1:String = "event:/SFX/Player/Land/PlayerLand1";
    public static inline var PlayerSkidLong:String = "event:/SFX/Player/Skid/PlayerSkidLong";
    public static inline var PlayerSkidShort:String = "event:/SFX/Player/Skid/PlayerSkidShort";
    public static inline var PlayerSlide:String = "event:/SFX/Player/Slide/PlayerSlide";
    public static inline var PlayerSlide2:String = "event:/SFX/Player/Slide/PlayerSlide2";
    public static inline var PlayerStep:String = "event:/SFX/Player/Step/PlayerStep";
}
