/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var LaserStationaryBlast:String = "event:/SFX/Enemies/LaserStationary/LaserStationaryBlast";
    public static inline var LaserStationaryBlast2:String = "event:/SFX/Enemies/LaserStationary/LaserStationaryBlast2";
    public static inline var LaserStationaryCharge:String = "event:/SFX/Enemies/LaserStationary/LaserStationaryCharge";
    public static inline var LaserTurretBlast:String = "event:/SFX/Enemies/LaserTurret/LaserTurretBlast";
    public static inline var LaserTurretBlast2:String = "event:/SFX/Enemies/LaserTurret/LaserTurretBlast2";
    public static inline var LaserTurretBlast3:String = "event:/SFX/Enemies/LaserTurret/LaserTurretBlast3";
    public static inline var LaserTurretCharge:String = "event:/SFX/Enemies/LaserTurret/LaserTurretCharge";
    public static inline var LaserTurretCharge2:String = "event:/SFX/Enemies/LaserTurret/LaserTurretCharge2";
    public static inline var DoorTick:String = "event:/SFX/Level/Door/DoorTick";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var PlayerJump1:String = "event:/SFX/Player/Jump/PlayerJump1";
    public static inline var PlayerJump2:String = "event:/SFX/Player/Jump/PlayerJump2";
    public static inline var PlayerJump3:String = "event:/SFX/Player/Jump/PlayerJump3";
    public static inline var PlayerJump3_2:String = "event:/SFX/Player/Jump/PlayerJump3_2";
    public static inline var PlayerJump4:String = "event:/SFX/Player/Jump/PlayerJump4";
    public static inline var PlayerLand1:String = "event:/SFX/Player/Land/PlayerLand1";
    public static inline var PlayerSkidLong:String = "event:/SFX/Player/Skid/PlayerSkidLong";
    public static inline var PlayerSkidShort:String = "event:/SFX/Player/Skid/PlayerSkidShort";
    public static inline var PlayerStep:String = "event:/SFX/Player/Step/PlayerStep";
}
